list_success = [
    "O  PRODUTO  FOI  CADASTRADO  COM  SUCESSO!",
    "O  PRODUTO  FOI  ATUALIZADO  COM  SUCESSO!",
    "O  PRODUTO  FOI  DELETADO  COM  SUCESSO!!!",
    "O  ESTOQUE  FOI  ATUALIZADO  COM  SUCESSO!",
    "O  OPERADOR  FOI  CADASTRADO  COM  SUCESSO",
    "O  OPERADOR  FOI  ATUALIZADO  COM  SUCESSO",
    "O  OPERADOR  FOI  DELETADO  COM  SUCESSO!!",
    "O  PRODUTO  FOI  ADICIONADO  COM  SUCESSO!",
    "A  VENDA  FOI  EFETUADA  COM  SUCESSO!!!! "
]